codestates-seb/seb45_pre_034

server/src/main/java/com/preproject/stackoverflow/answer/entity/Answer.java

- #30 
연관 관계 연결은 백엔드 분들 엔티티가 전부 완성되면 연결할 예정 입니다.

:sparkles: BE_30) 답변 엔티티 생성

---

server/build.gradle

mapper를 사용하기 위해 dependency를 추가하였습니다.

:arrow_up: BE_31) mapstruct dependency 추가

---

server/src/main/java/com/preproject/stackoverflow/comment/entity/Comment.java

:bug: 댓글 엔티티 오류 코드 수정

---

server/src/main/java/com/preproject/stackoverflow/answer/entity/Answer.java
server/src/main/java/com/preproject/stackoverflow/comment/entity/Comment.java
server/src/main/java/com/preproject/stackoverflow/exception/BusinessLogicException.java
server/src/main/java/com/preproject/stackoverflow/exception/ExceptionCode.java
server/src/main/java/com/preproject/stackoverflow/question/controller/QuestionController.java
server/src/main/java/com/preproject/stackoverflow/question/dto/QuestionPatchDto.java
server/src/main/java/com/preproject/stackoverflow/question/dto/QuestionPostDto.java
server/src/main/java/com/preproject/stackoverflow/question/entity/Question.java
server/src/main/java/com/preproject/stackoverflow/question/mapper/QuestionMapper.java
server/src/main/java/com/preproject/stackoverflow/question/repository/QuestionRepository.java
server/src/main/java/com/preproject/stackoverflow/question/service/QuestionService.java

- #51 #37 #14 #16 #15 #13 
전체적인 큰 틀만 만들었기에 아직 기능들은 작동하지 않습니다.
컨트롤러 부분에서 먼저 POST 기능을 구현하는데, 현재 spring sequrity 부분에서 막고있어 이부분을 수정해야 할 것 같습니다.

:sparkles: question 컨트롤러, Dto, 리포지토리, 서비스 큰 틀 추가

---

server/src/main/java/com/preproject/stackoverflow/answer/controller/AnswerController.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/AnswerResponseDto.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/QuestionAnswerResponseDto.java
server/src/main/java/com/preproject/stackoverflow/answer/mapper/AnswerMapper.java
server/src/main/java/com/preproject/stackoverflow/answer/repository/AnswerRepository.java
server/src/main/java/com/preproject/stackoverflow/answer/service/AnswerService.java

- #54 
- url: /answer?questionId={questionId}
- method: GET
- 기능: 특정 질문에 대한 전체 답변 출력 메서드
- response body
```
{
"questionId" : 1,
"answerId" : 1,
"body" : "이 질문에 대한 답은 ~",
"recommend" :  3,
"status" : false
}
```

BE_52) 답변 기초틀 작성

---

client/src/app/component/layout/Layout.jsx
client/src/app/component/layout/Layout.module.css
client/src/app/component/questions/QuestionsList.jsx
client/src/app/component/questions/QuestionsList.module.css
client/src/app/page.jsx
client/src/app/questions/page.jsx

- #58 
- QuestionSummary.jsx 
- SortHandler.jsx
- Ask Question 버튼도 컴포넌트 하게되면 
QuestionsList.jsx에 추가할 예정입니다.

FE _58)_QuestionsList 컴포넌트

---

server/src/main/java/com/preproject/stackoverflow/answer/controller/AnswerController.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/AnswerPatchDto.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/AnswerPostDto.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/UserAnswerResponseDto.java
server/src/main/java/com/preproject/stackoverflow/answer/mapper/AnswerMapper.java
server/src/main/java/com/preproject/stackoverflow/exception/ExceptionCode.java

BE_70) 답변 매퍼 작성

---

client/src/app/component/common/SortHandler.jsx
client/src/app/component/common/SortHandler.module.css
client/src/app/component/questions/QuestionsList.jsx
client/src/app/component/questions/QuestionsList.module.css

[FE]✨ 65) SortHandler 컴포넌트

---

server/src/main/java/com/preproject/stackoverflow/answer/mapper/AnswerMapper.java
server/src/main/java/com/preproject/stackoverflow/answer/service/AnswerService.java

[BE] 🔧  70, 72) 답변 매퍼 작성, 답변 서비스 작성

---

server/src/main/java/com/preproject/stackoverflow/answer/controller/AnswerController.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/AnswerPostDto.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/QuestionAnswerResponseDto.java
server/src/main/java/com/preproject/stackoverflow/answer/entity/Answer.java

[BE] 89) 답변 리팩토링

---

server/src/main/java/com/preproject/stackoverflow/answer/controller/AnswerController.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/AnswerPatchDto.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/AnswerPostDto.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/QuestionAnswerResponseDto.java
server/src/main/java/com/preproject/stackoverflow/answer/dto/UserAnswerResponseDto.java
server/src/main/java/com/preproject/stackoverflow/answer/repository/AnswerRepository.java
server/src/main/java/com/preproject/stackoverflow/answer/service/AnswerService.java

- #97 
- url: {url}/answers
- method: GET
- 기능: 페이지네이션 기능을 이용한 답변 response
- response body
```
{
"data": [
{
"answerId": 1,
"questionId": 1,
"userId": 1,
"body": "2",
"recommend": 10,
"status": true,
"createdAt": "2023-08-17T12:34:56",
"modifiedAt": "2023-08-17T12:34:56"
},
{
"answerId": 2,
"questionId": 1,
"userId": 2,
"body": "1",
"recommend": 5,
"status": true,
"createdAt": "2023-08-17T12:45:00",
"modifiedAt": "2023-08-17T12:45:00"
}
],
"page": {
"size": 10,
"totalElements": 50,
"totalPages": 5,
"number": 0
}
}
```
DB 연동, 연동후 확인

[BE] 97_답변 페이지네이션 추가

---

client/src/app/component/questions/QuestionSummary.jsx
client/src/app/component/questions/QuestionSummary.module.css
client/src/app/component/questions/QuestionsList.jsx

[FE] 87) ✨ QuestionSummary 컴포넌트

---

client/package-lock.json
client/package.json
client/src/app/component/layout/Header.jsx
client/src/app/component/layout/Header.module.css
client/src/app/component/layout/Layout.jsx
client/src/app/component/layout/Layout.module.css
client/src/app/component/layout/Navigation.jsx
client/src/app/component/layout/Navigation.module.css
client/src/app/component/user/ActivityItem.jsx
client/src/app/component/user/ActivityItem.module.css
client/src/app/component/user/UserCard.jsx
client/src/app/component/user/UserCard.module.css
client/src/app/recoil/Global.js
client/src/app/users/[nickname]/UserDetail.module.css
client/src/app/users/[nickname]/mockdata.js
client/src/app/users/[nickname]/page.jsx

- #80 
- ![image](https://github.com/codestates-seb/seb45_pre_034/assets/126226314/b920aa27-0ffc-479b-967c-c701ba9c1379)
- 질문 및 질문에 대한 답변에 대해 "#"을 이용한 url로 원하는 위치로 이동할 수 있도록 하는 부분 공부 필요
- 반응형 적용 필요
- view ### answers 버튼 추가 필요
- 버튼 타고 넘어가서 전체 리스트를 보여주는 화면 필요

[FE] 💄 80) 유저 상세 화면

---

server/src/main/java/com/preproject/stackoverflow/answer/entity/Answer.java

- #88 
유저 엔티티 완성 이후 유저 연관관계 추가 예정

[BE] :recycle: 88) 답변 연관관계 추가

---

client/src/app/component/common/MdViewer.jsx
client/src/app/component/common/Mde.jsx
client/src/app/component/layout/Layout.module.css
client/src/app/component/questions/QuestionPost.jsx
client/src/app/component/questions/QuestionSummary.jsx
client/src/app/questions/[id]/page.jsx
client/src/app/questions/page.jsx

- #103 
- ![image](https://github.com/codestates-seb/seb45_pre_034/assets/85207564/0b3ca83e-191e-4f93-a3de-e09d749ae270)
-

[FE] 🛠️  마크다운 웹에디터 개선 및 뷰어 컴포넌트 추가

---

client/src/app/component/questions/QuestionAsk.jsx
client/src/app/component/questions/QuestionAsk.module.css
client/src/app/questions/ask/page.jsx

- #94 
원본 스택오버플로우의 질문 작성 페이지의 마지막 요소
기존에 작성된 질문과 중복되는 내용인지 검사하는 기능으로 추정됨
일단 제외하고 진행하겠습니다

[FE] 93) ✨ 질문 작성 컴포넌트 & 페이지

---

client/src/app/component/comment/Comment.jsx
client/src/app/component/comment/Comment.module.css
client/src/app/component/questions/QuestionPost.jsx

[FE] ✨ Comment 컴포넌트 추가

---

server/src/main/java/com/preproject/stackoverflow/member/controller/UserController.java
server/src/main/java/com/preproject/stackoverflow/member/dto/LoginPostDto.java
server/src/main/java/com/preproject/stackoverflow/member/dto/MemberPatchDto.java
server/src/main/java/com/preproject/stackoverflow/member/dto/SignupPostDto.java
server/src/main/java/com/preproject/stackoverflow/member/entity/SignupEntity.java
server/src/main/java/com/preproject/stackoverflow/member/mapper/MemberMapper.java
server/src/main/java/com/preproject/stackoverflow/member/service/MemberService.java

#33 #34 #35
User 컨트롤러, 회원정보 엔티티, Dto 등 // 미완성

User 컨트롤러, 회원정보 엔티티, Dto 등 // 미완성

---

client/.gitignore
client/.vscode/launch.json
client/next.config.js
client/package.json
client/src/app/component/layout/Header.jsx
client/src/app/component/layout/Layout.module.css
client/src/app/component/sign/create/PickProfile.jsx
client/src/app/component/user/list/SearchSection.jsx
client/src/app/component/user/list/SearchSection.module.css
client/src/app/component/user/list/UserItem.jsx
client/src/app/component/user/list/UserItem.module.css
client/src/app/users/Users.module.css
client/src/app/users/page.jsx

- #26 
- ![image](https://github.com/codestates-seb/seb45_pre_034/assets/126226314/c6eb9680-5e1f-4d0f-b779-418cedea3f28)
- [api 요청하여 dummy data 받을 수 있는 dummyJson 문서](https://dummyjson.com/docs/users)
- 다음은 api 요청 코드입니다. [참고한 코드](https://stackoverflow.com/a/76292138)
- 코드 확인 전 이 두가지 꼭 기억해 주세요!
- **`1. SSR은 크롬 네트워크 탭에 api 요청 기록이 뜨지 않아요`**
- api 통신 내역이 크롬 개발자 도구 네트워크 탭에 뜨지 않았던 이유는 SSR이기 때문입니다.
- SSR은 Server Side Rendering이기 때문에 데이터를 받고 나서 html 을 만들고, 브라우저에 전달합니다.
- 따라서 브라우저가 렌더링될 때는 이미 데이터를 받고 난 후이기 때문에 크롬 개발자 도구 네트워크 탭에 뜨지 않았던 것입니다.
- **`2. `console.log(users)` 로그 기록은 크롬 콘솔 탭에 뜨는 것이 아닌 npm run dev 를 실행시킨 터미널에 뜹니다.`**
- 더 자세한 내용은 [해당 스택오버플로우 답글](https://stackoverflow.com/a/76863089)에서 확인 부탁드립니다!
어찌보면 당연한 얘기인데, 리액트 개발에 익숙하다보니 크롬만 계속 확인하여 데이터가 잘 도착한 사실을 몰랐었네요😂
```
export const fetchUsers = …
```

[FE] 💄 26) api 호출 테스트 + 유저 리스트 화면 추가

---

client/src/app/component/edit/Edit.jsx
client/src/app/component/edit/edit.module.css

[FE] 119) 컴포넌트 추가 및 분기 설계
